name: Sync to Vercel Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Remove workflow files
        run: |
          rm -rf .github/workflows
          
      - name: Push to warmace101/team17
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.SECOND_REPO_TOKEN }}
          repository: warmace101/team17
          branch: main
          force: true
