name: Sync to Vercel Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Remove workflow directory
        run: rm -rf .github/workflows
        
      - name: Push to Vercel repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.SECOND_REPO_TOKEN }}
        with:
          source-directory: '.'
          destination-github-username: 'warmace101'
          destination-repository-name: 'team17'
          user-email: actions@github.com
          target-branch: main
